// <auto-generated />
namespace MonoGameWepAPI.Database.GameDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Initialise : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialise));
        
        string IMigrationMetadata.Id
        {
            get { return "201501181523174_Initialise"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
